default_language_version:
  python: python3.7
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: venv/bin/black
        language: python
        types: [python]
        args: []
        require_serial: false
        additional_dependencies: []

      - id: isort
        name: isort
        entry: venv/bin/isort
        language: python
        types: [python]
        args: []
        require_serial: false
        additional_dependencies: []

      - id: flake8
        name: flake8
        entry: venv/bin/flake8
        language: python
        types: [python]
        args: []
        require_serial: false
        additional_dependencies: []

      - id: pylint
        name: pylint
        entry: venv/bin/pylint
        language: python
        types: [python]
        args: []
        require_serial: false
        additional_dependencies: []