name: Run tests and linters

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Run containers
      run: make test-services-up

    - name: Build
      run: go build -v ./...

    - name: Set up migrations
      run: make migrate-up-tests

    - name: Test
      run: make test-sequentially